apiVersion: apps/v1
kind: Deployment
metadata:
  name: mt-frontend
  namespace: mt-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mt-frontend
  template:
    metadata:
      labels:
        app: mt-frontend
    spec:
      containers:
      - name: mt-frontend
        image: talha0pse/mt-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mt-frontend-service
  namespace: mt-project
spec:
  type: LoadBalancer
  selector:
    app: mt-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
