name: Deploy to EKS

on:
  push:
    branches:
      - main  # Or the branch you use for production, e.g., master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: ~/.cache/docker
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push Docker image
      run: |
        docker build -t talha0pse/mt-backend:${{ github.sha }} .
        docker push talha0pse/mt-backend:${{ github.sha }}
    
    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
    
    - name: Set kubeconfig
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yml
        export KUBECONFIG=kubeconfig.yml
    
    - name: Update EKS deployment with new image
      run: |
        kubectl set image deployment/backend-deployment backend=talha0pse/mt-backend:${{ github.sha }}
        kubectl set image deployment/frontend-deployment frontend=talha0pse/mt-frontend:${{ github.sha }}
        kubectl rollout status deployment/backend-deployment
        kubectl rollout status deployment/frontend-deployment
